# GitHub Actions and `just build` use this matrix of firmware targets.
---
include:
  - board: zaphod
  - board: technikable
  - board: planck@6.0.0//zmk
    artifact-name: planck_rev6
  - board: nice_nano
    shield: neo_kinesis
  - board: nice_nano
    shield: cradio_left
  - board: nice_nano
    shield: cradio_right
